  repos:
    - repo: https://github.com/compilerla/conventional-pre-commit
      rev: v4.4.0
      hooks:
        - id: conventional-pre-commit
          stages: [commit-msg]
          args: [feat, fix, chore, docs, style, refactor, test, build, ci, perf, revert]

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
        - id: check-json
        - id: check-merge-conflict
        - id: check-yaml
          args: ['--unsafe']
        - id: end-of-file-fixer
          exclude: ^sts-mock/sts\.yaml$
        - id: mixed-line-ending
          exclude: ^sts-mock/sts\.yaml$
        - id: trailing-whitespace
          exclude: ^sts-mock/sts\.yaml$

    - repo: https://github.com/bridgecrewio/checkov.git
      rev: 3.2.529
      hooks:
        - id: checkov
          verbose: true
          files: ^sts-mock/template\.yaml$

        - id: checkov
          verbose: true
          files: ^txma-mock/template\.yaml$

        - id: checkov
          verbose: true
          files: ^status-list--mock/template\.yaml$

    - repo: https://github.com/aws-cloudformation/cfn-lint
      rev: v1.51.0
      hooks:
        - id: cfn-lint-rc
          files: ^sts-mock/template\.yaml$

        - id: cfn-lint-rc
          files: ^txma-mock/template\.yaml$

    - repo: https://github.com/aws-cloudformation/rain
      rev: v1.24.4
      hooks:
        - id: rain-format
          files: ^sts-mock/template\.yaml$

        - id: rain-format
          files: ^txma-mock/template\.yaml$

        - id: rain-format
          files: ^status-list--mock/template\.yaml$

    - repo: local
      hooks:
        - id: status-list-mock-eslint-ts
          name: Status List Mock - ESLint linter
          language: system
          entry: bash -c 'cd status-list-mock && npm run lint'
          files: ^status-list-mock/.*\.(ts|md)$
          stages: [pre-commit]

        - id: status-list-mock-prettier-ts
          name: Status List Mock - Prettier format check
          language: system
          entry: bash -c 'cd status-list-mock && npm run format:check'
          files: ^status-list-mock/.*\.(ts|md|yaml)$
          stages: [pre-commit]

        - id: status-list-mock-jest-tests
          name: Status List Mock - Jest unit tests
          language: system
          entry: bash -c 'cd status-list-mock && npm run test'
          files: ^status-list-mock/.*\.ts$
          stages: [pre-push]
