openapi: 3.0.0
info:
  title: GOV.UK One Login Status List - Public API
  version: 1.0.0
  description: Public endpoints for retrieving status lists
paths:
  /t/{statusListIdentifier}:
    get:
      description: A public endpoint that returns an IETF Token Status List JWT. The list that is returned depends on the list type for the GOV.UK Wallet credential issuer agreed at the time of registration. The response has a signed JWT in one of the two supported status list formats.
      parameters:
        - in: path
          name: statusListIdentifier
          schema:
            type: string
            example: "A671FED3E9AD"
          required: true
          description: "Unique name representing the specific status list"
      responses:
        "200":
          description: "OK"
          content:
            application/statuslist+jwt:
              schema:
                type: string
                description: Signed IETF Token Status List JWT containing the status list.
              example: <JWT>
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusList404ErrorResponse"
              example:
                error: NOT_FOUND
                error_description: "Status List not found for endpoint uri"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusList500ErrorResponse"
              example:
                error: INTERNAL_SERVER_ERROR
                error_description: "..."
components:
  schemas:
    StatusList404ErrorResponse:
      type: object
      properties:
        error:
          description: An error code - must be `NOT_FOUND`.
          type: string
        error_description:
          description: A human-readable explanation of the error.
          type: string
      required:
        - error
    StatusList500ErrorResponse:
      type: object
      properties:
        error:
          description: An error code - must be `INTERNAL_SERVER_ERROR`.
          type: string
        error_description:
          description: A human-readable explanation of the error.
          type: string
      required:
        - error
