AWSTemplateFormatVersion: "2010-09-09"

Description: Mock of the Mobile Platform /txma-event endpoint.

Parameters:
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - dev
      - build
      - integration
    Default: dev

Mappings:
  EnvironmentVariables:
    dev:
      SelfUrl: txma-mock.wallet-onboarding.dev.account.gov.uk
    build:
      SelfUrl: txma-mock.wallet-onboarding.build.account.gov.uk
    integration:
      SelfUrl: txma-mock.wallet-onboarding.integration.account.gov.uk

Conditions:
  StackNameIsWalletTxMAMock: !Equals
    - !Ref AWS::StackName
    - wallet-txma-mock

  IsIntegration: !Equals
    - !Ref Environment
    - integration

Transform: AWS::Serverless-2016-10-31

Resources:
  MockApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub ${AWS::StackName}-${Environment}
      EndpointConfiguration:
        Types:
          - REGIONAL

  TxmaEventResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MockApi
      ParentId: !GetAtt MockApi.RootResourceId
      PathPart: txma-event

  TxmaHealthcheckResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MockApi
      ParentId: !GetAtt MockApi.RootResourceId
      PathPart: txma-healthcheck

  TxmaEventPostMethod:
    Type: AWS::ApiGateway::Method
    Metadata:
      checkov:
        skip:
          - id: CKV_AWS_59
            rule: Ensure there is no open access to back-end resources through API
            comment: The API Gateway is set up as a mock integration, so there are no back-end resources that can be accessed through it.
    Properties:
      RestApiId: !Ref MockApi
      ResourceId: !Ref TxmaEventResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: Empty

  TxmaHealthcheckGetMethod:
    Type: AWS::ApiGateway::Method
    Metadata:
      checkov:
        skip:
          - id: CKV_AWS_59
            rule: Ensure there is no open access to back-end resources through API
            comment: The API Gateway is set up as a mock integration, so there are no back-end resources that can be accessed through it.
    Properties:
      RestApiId: !Ref MockApi
      ResourceId: !Ref TxmaHealthcheckResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: Empty

  OptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId: !Ref MockApi
      ResourceId: !Ref TxmaHealthcheckResource
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
              method.response.header.Access-Control-Allow-Methods: '''GET,OPTIONS'''
              method.response.header.Access-Control-Allow-Origin: '''*'''
            ResponseTemplates:
              application/json: ""
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: Empty
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  MockApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - TxmaEventPostMethod
      - TxmaHealthcheckGetMethod
      - OptionsMethod
    Properties:
      RestApiId: !Ref MockApi

  MockApiStage:
    Type: AWS::ApiGateway::Stage
    Metadata:
      checkov:
        skip:
          - id: CKV_AWS_120
            rule: Ensure API Gateway caching is enabled
            comment: Caching is not required for this API Gateway, and skiping this rule will save caching costs.
    Properties:
      RestApiId: !Ref MockApi
      DeploymentId: !Ref MockApiDeployment
      StageName: !Ref Environment
      TracingEnabled: true
      AccessLogSetting:
        DestinationArn: !GetAtt TxmaApiGatewayAccessLogsGroup.Arn
        Format: '{ "requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod", "path": "$context.path", "routeKey":"$context.routeKey", "status":"$context.status", "protocol":"$context.protocol", "responseLength":"$context.responseLength" }'

  CustomDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !If
        - StackNameIsWalletTxMAMock
        - !FindInMap
          - EnvironmentVariables
          - !Ref Environment
          - SelfUrl
        - !Sub
          - ${AWS::StackName}-${SelfUrl}
          - SelfUrl: !FindInMap
              - EnvironmentVariables
              - !Ref Environment
              - SelfUrl
      RegionalCertificateArn: !Sub '{{resolve:ssm:/${Environment}/Platform/ACM/PrimaryZoneWildcardCertificateARN}}'
      EndpointConfiguration:
        Types:
          - REGIONAL
      SecurityPolicy: TLS_1_2

  BasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: MockApiStage
    Properties:
      DomainName: !Ref CustomDomain
      RestApiId: !Ref MockApi
      Stage: !Ref Environment

  ApiRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref CustomDomain
      Type: A
      HostedZoneId: !Sub '{{resolve:ssm:/${Environment}/Platform/Route53/PrimaryZoneID}}'
      AliasTarget:
        DNSName: !GetAtt CustomDomain.RegionalDomainName
        HostedZoneId: !GetAtt CustomDomain.RegionalHostedZoneId
        EvaluateTargetHealth: false

  TxmaApiGatewayAccessLogsGroup:
    Type: AWS::Logs::LogGroup
    Metadata:
      checkov:
        skip:
          - id: CKV_AWS_158
            rule: Ensure that CloudWatch Log Group is encrypted by KMS
            comment: KMS encryption not required as log group will not contain sensitive data.
    Properties:
      LogGroupName: !Sub /aws/apigateway/${AWS::StackName}-api-gateway-access-logs
      RetentionInDays: 14

  TXMAMockHeartbeatAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-TXMAMockHeartbeatAlarm
      AlarmDescription: 'TXMAMock-Heartbeat Synthetic-Canary Alarm: Failed  GreaterThanOrEqualToThreshold 1'
      MetricName: Failed
      Namespace: CloudWatchSynthetics
      Dimensions:
        - Name: CanaryName
          Value: txma_mock_heartbeat
      Period: 60 # 1 minute in seconds
      EvaluationPeriods: 1
      Statistic: Maximum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1.0
      TreatMissingData: ignore
      ActionsEnabled: true
      AlarmActions:
        - !ImportValue alarm-sns-topic-warning
      OKActions:
        - !ImportValue alarm-sns-topic-warning
    Condition: IsIntegration

Outputs:
  TxMAMockFriendlyUrl:
    Description: Friendly URL for the deployed TxMA mock
    Value: !If
      - StackNameIsWalletTxMAMock
      - !FindInMap
        - EnvironmentVariables
        - !Ref Environment
        - SelfUrl
      - !Sub
        - ${AWS::StackName}-${SelfUrl}
        - SelfUrl: !FindInMap
            - EnvironmentVariables
            - !Ref Environment
            - SelfUrl
