name: Notify Slack on Failure

on:
  workflow_call:
    secrets:
      GH_WORKFLOW_FAILURE_BOT_SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify-slack-on-failure:
    name: Notify Slack on Failure
    runs-on: ubuntu-24.04
    permissions: {}
    steps:
      - name: Send Slack alert
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        with:
          webhook: ${{ secrets.GH_WORKFLOW_FAILURE_BOT_SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            "repository": "${{ github.repository }}"
            "run": ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
