name: Run Checkov Static Analysis
on:
  workflow_call:
    inputs:
      file-to-scan:
        required: true
        type: string

jobs:
  run-checkov:
    name: Run Checkov
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@7b972723c44fb3d256283fac96fae5d7c1894bb7 # v12.3114.0
        with:
          file: ${{ inputs.file-to-scan }}
          quiet: true
          soft_fail: false
