name: Run Checkov Static Analysis
on:
  workflow_call:
    inputs:
      file-to-scan:
        required: true
        type: string

jobs:
  run-checkov:
    name: Run Checkov
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@5798bad4f6dd9c1fb67ae3ec10d42d8fb67037c4 # v12.3126.0
        with:
          file: ${{ inputs.file-to-scan }}
          quiet: true
          soft_fail: false
