name: Status List Mock - Push to Main

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - status-list-mock/**
      - .github/workflows/status-list-mock-push-to-main.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-sam-template-formatting:
    name: Check SAM template formatting
    uses: ./.github/workflows/check-sam-template-formatting.yml
    with:
      working-directory: ./status-list-mock

  run-checkov:
    name: Run Checkov
    uses: ./.github/workflows/run-checkov.yml
    with:
      file-to-scan: status-list-mock/template.yaml

  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ./status-list-mock
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.gitRef }}

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: status-list-mock/.nvmrc
          cache: npm
          cache-dependency-path: status-list-mock/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectBaseDir: ./status-list-mock

      - name: SonarQube Quality Gate check
        uses: SonarSource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b # v1.2.0
        timeout-minutes: 15
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          scanMetadataReportFile: status-list-mock/.scannerwork/report-task.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: ${{ secrets.BUILD_STATUS_LIST_MOCK_GH_ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@89ddb14d60e682855e3fea4be85b3c56485de310 # v3
        with:
          projectBaseDir: ./status-list-mock
          version: 1.132.0
          use-installer: true

      - name: Validate SAM template
        run: |
          echo "SAM_CLI_TELEMETRY=0" >> $GITHUB_ENV
          sam validate --lint

      - name: Build SAM template
        run: sam build --parallel

      - name: Upload SAM artifacts
        # Upload the built SAM application artifacts to the deployment pipeline S3 bucket
        uses: govuk-one-login/devplatform-upload-action@5879c30205266ad61e8299a4fcea76364530c9c1 # v3.14.0
        with:
          artifact-bucket-name: ${{ secrets.BUILD_STATUS_LIST_MOCK_GH_ARTIFACT_SOURCE_BUCKET_NAME }}
          signing-profile-name: ${{ secrets.BUILD_STATUS_LIST_MOCK_SIGNING_PROFILE_NAME }}
          template-file: .aws-sam/build/template.yaml
          working-directory: ./status-list-mock
