name: STS Mock - Pull Request Checks

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
    paths:
      - sts-mock/**
      - .github/workflows/sts-mock-pull-request-checks.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check-sam-template-formatting:
    name: Check SAM template formatting
    uses: ./.github/workflows/check-sam-template-formatting.yml
    with:
      working-directory: ./sts-mock

  validate-docker-image:
    name: Validate Docker image
    uses: ./.github/workflows/validate-docker-image.yml
    with:
      working-directory: ./sts-mock

  validate-and-build-sam-template:
    name: Validate and build SAM template
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: read
    env:
      SAM_CLI_TELEMETRY: 0
    defaults:
      run:
        working-directory: ./sts-mock
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@89ddb14d60e682855e3fea4be85b3c56485de310 # v3
        with:
          version: 1.155.2
          use-installer: true

      - name: Validate SAM template
        run: sam validate --lint

      - name: Build SAM template
        run: sam build

  run-checkov:
    name: Run Checkov
    uses: ./.github/workflows/run-checkov.yml
    with:
      file-to-scan: sts-mock/template.yaml

  check-oas-for-drift:
    name: Check STS Back OAS for drift
    uses: ./.github/workflows/sts-mock-check-oas-for-drift.yml
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    secrets:
      WALLET_STS_BACK_DEPLOY_KEY: ${{ secrets.WALLET_STS_BACK_DEPLOY_KEY }}
      GH_WORKFLOW_FAILURE_BOT_SLACK_WEBHOOK_URL: ${{ secrets.GH_WORKFLOW_FAILURE_BOT_SLACK_WEBHOOK_URL }}
