name: TxMA Event Mock - Manual Deployment to Dev

on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: Input branch name or commit SHA
        required: true
        type: string
        default: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
    env:
      SAM_CLI_TELEMETRY: 0
    defaults:
      run:
        working-directory: ./txma-mock
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # Check out the repository at the specific branch, tag, or commit
          ref: ${{ inputs.gitRef }}

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@f84ec7d548307efafe33230528756de3c5841a17 # v2
        with:
          version: 1.155.2
          use-installer: true

      - name: Validate SAM template
        run: sam validate --lint

      - name: Build SAM template
        run: sam build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          role-to-assume: ${{ secrets.DEV_TXMA_MOCK_GH_ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@5879c30205266ad61e8299a4fcea76364530c9c1 # v3.14.0
        with:
          artifact-bucket-name: ${{ secrets.DEV_TXMA_MOCK_GH_ARTIFACT_SOURCE_BUCKET_NAME }}
          working-directory: ./txma-mock
          template-file: .aws-sam/build/template.yaml