name: TxMA Event Mock - Push to Main

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - txma-mock/**
      - .github/workflows/txma-mock-push-to-main.yml

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check-sam-template-formatting:
    name: Check SAM template formatting
    uses: ./.github/workflows/check-sam-template-formatting.yml
    with:
      working-directory: ./sts-mock

  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
    env:
      SAM_CLI_TELEMETRY: 0
    defaults:
      run:
        working-directory: ./txma-mock
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@89ddb14d60e682855e3fea4be85b3c56485de310 # v3
        with:
          version: 1.155.2
          use-installer: true
      
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@9201a8e6eaa919e3444d7c4ca691896efde4f033 # v12.3101.0
        with:
          file: "txma-mock/template.yaml"
          quiet: true
          soft_fail: false

      - name: Validate SAM template
        run: sam validate --lint

      - name: Build SAM template
        run: sam build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          role-to-assume: ${{ secrets.BUILD_TXMA_MOCK_GH_ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@5879c30205266ad61e8299a4fcea76364530c9c1 # v3.14.0
        with:
          artifact-bucket-name: ${{ secrets.BUILD_TXMA_MOCK_GH_ARTIFACT_SOURCE_BUCKET_NAME }}
          signing-profile-name: ${{ secrets.BUILD_TXMA_MOCK_SIGNING_PROFILE_NAME }}
          working-directory: ./txma-mock
          template-file: .aws-sam/build/template.yaml