name: TxMA Event Mock - Pull Request Checks

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
    paths:
      - txma-mock/**
      - .github/workflows/txma-mock-pull-request-checks.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check-sam-template-formatting:
    name: Check SAM template formatting
    uses: ./.github/workflows/check-sam-template-formatting.yml
    with:
      working-directory: ./txma-mock

  validate-and-build-sam-template:
    name: Validate and build SAM template
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: read
    env:
      SAM_CLI_TELEMETRY: 0
    defaults:
      run:
        working-directory: ./txma-mock
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@d78e1a4a9656d3b223e59b80676a797f20093133 # v2
        with:
          version: 1.155.2
          use-installer: true

      - name: Validate SAM template
        run: sam validate --lint

      - name: Build SAM template
        run: sam build
