name: Validate Docker Image

on:
  workflow_call:
    inputs:
      working-directory:
        type: string

jobs:
  validate-docker-image:
    name: Validate Docker image
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build Docker image
        run: docker build -t image .
