name: Validate Docker Image

on:
  workflow_call:
    inputs:
      working-directory:
        type: string

jobs:
  validate-docker-image:
    name: Validate Docker image
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Build Docker image
        run: docker build -t image .
